### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by andersondn** [andreszs/cordova-plugin-sms-receive#1]
The following files are not found: 
scripts/platformOverrides.js
scripts/index.js

**Comment by andreszs** [comment]
You are right, I have just uploaded those files to the [demo/scripts](https://github.com/andreszs/cordova-plugin-sms-receive/tree/master/demo/scripts) folder. 

Thank you for reporting this, the demo should work now with those files.

**Comment by andreszs** [comment]
Just in case someone lands here, there is a new pre-compiled [plugin demo app](https://www.andreszsogon.com/cordova-sms-receive-plugin-demo/).
