### ISSUE TITLE
SMS event is not getting called if the message app on android is receiving the SMS 

### ISSUE THREAD

**Issue by moghribalakrishna** [andreszs/cordova-plugin-sms-receive#10]
I am able to get the event called only when I disable the SMS permission on the default message app on my phone.

hardware: Xiaomi  Redmi 5A
Android version: 8.1.0

  It was earlier working but now after updating my phone it's behaving strangely, I am pending a release & this is one of the most important.
  Quick help here would be a great help.

Thanks in advance!

**Comment by andreszs** [comment]
Hi, please try plugin version 2.0.0 released today. It has been tested in Xiaomi Redmi 9 with Android 10 and many other devices.
