### ISSUE TITLE
App rejected from google play store

### ISSUE THREAD

**Issue by sbchopade** [andreszs/cordova-plugin-sms-receive#11]
Hi,
I used this plugin in Ionic 4 app to read OTP. Everything was working as expected , but unfortunately google play store has changed its policies that why they rejected my application. So what should i do now. I only want this plugin in my app not any other. Is there any way to solve this problem. In google pay they were asking for some reason to use this plugin. I don't  know exactly what I have had selected. Can you please help me?

**Comment by steveaze** [comment]
Hi @sbchopade! Did you ever find a solution? We are thinking of using this service in an app we are building

**Comment by sbchopade** [comment]
@steveaze No, I didn't. I had to remove all code of retrieving OTP from sms.

**Comment by andreszs** [comment]
@sbchopade Please switch to the **[cordova-plugin-sms-retriever](https://github.com/andreszs/cordova-plugin-sms-retriever)** plugin which uses the Android [SMS Retriever API](https://developers.google.com/identity/sms-retriever/overview) to validate verification codes received, without requestion SMS permission and without compromising the user's privacy.
