### ISSUE TITLE
IMPORTANT this plugin has been superseded by the SMS Retriever plugin

### ISSUE THREAD

**Issue by andreszs** [andreszs/cordova-plugin-sms-receive#12]
## Important Notice to Plugin Users

This legacy SMS receive plugin has been deprecated and it **must not** be used anymore for production environments. This is due to a change in the Android SMS permission policy which prevents the non-default SMS app from reading any SMS contents, for privacy reasons.

To retrieve SMS contents you must switch to my **[cordova-plugin-sms-retriever](https://github.com/andreszs/cordova-plugin-sms-retriever) plugin**, based on the [SMS Retriever API](https://developers.google.com/identity/sms-retriever/overview). A sample Cordova app is included in the repository.

## About the SMS Retriever API

This API lets you read an **individual SMS** that was specifically targeted to your app alone, by including a unique app ID string in the SMS contents.

The SMS Retriever API **does not** require SMS permission to work, and it has been developed specifically to fix the SMS privacy issues created by malicious apps and games that used to request SMS permission and could therefore steal all SMS contents from its users.

Kindly switch plugins right away if you are still using the current plugin, otherwise Google Play Store will reject your app at any moment.

**Comment by noriellecruz** [comment]
This plugin is still feasible for developers that doesn't need to publish their apps on google play. Please continue maintaining SMS receive plugin, thank you.

**Comment by sachi097** [comment]
Yes I completely agree with @noriellecruz . @andreszs  please continue maintaining SMS receive plugin this would help developers who do not wish to publish apps on google play store. 
Thank you in advance.

**Comment by andreszs** [comment]
Thanks for your feedback. I have updated the plugin to version 2.0.0 with several fixes, and a new plugin demo app has been released as well.
