### ISSUE TITLE
SMS message gettng cut off after 153 characters

### ISSUE THREAD

**Issue by primarchsolutions** [andreszs/cordova-plugin-sms-receive#15]
I am using the plugin to read incoming messages but the message gets cut off after 153 characters. is there a way to capture the full SMS?

`  start() {
	//this.global.createAddressTable();		  
    SMSReceive.startWatch(
      () => {
		this.captureStatus = true;  
        alert('watch started');
        document.addEventListener('onSMSArrive', (e: any) => {
          alert(JSON.stringify(e.data));
		  //alert('onSMSArrive()');
          var IncomingSMS = e.data;
          //alert('sms.address:' + IncomingSMS.address);
          //alert('sms.body:' + IncomingSMS.body);
          /* Debug received SMS content (JSON) */
          alert(JSON.stringify(IncomingSMS));
          //this.processSMS(IncomingSMS);
        });
      },
      () => { alert('watch start failed') }
    )
  }`

**Comment by andreszs** [comment]
Hi, please download version 2.0.0 which fixed this and other issues as well.
