### ISSUE TITLE
Remove listener

### ISSUE THREAD

**Issue by pcsantana** [andreszs/cordova-plugin-sms-receive#2]
Hi,

Thanks for the plugin!
I'm facing a problem with the "onSMSArrive" listener.
Even if I call "stopWatch" method or/and "document.removeEventListener('onSMSArrive')" the listener stills alive and call many times.

Any tips to solve this?
Thank you.

**Comment by andreszs** [comment]
Sorry, I'm not sure why you are experiencing that issue, it worked fine on Android 4.4.2, 5.1 and 6.0 last time I tested the sample app (today), with cordova 6.5.0 and cordova-android 6.3.0.

**Comment by mateo2181** [comment]
> Hi,
> 
> Thanks for the plugin!
> I'm facing a problem with the "onSMSArrive" listener.
> Even if I call "stopWatch" method or/and "document.removeEventListener('onSMSArrive')" the listener stills alive and call many times.
> 
> Any tips to solve this?
> Thank you.

Did you solve this? I have the same problem. Thanks!
