### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mazzimi** [andreszs/cordova-plugin-sms-receive#3]
Hello,

trying to install the plugin to a cordova ioniv v1 project I get a strange error

I use this command:
cordova plugin add cordova-plugin-sms-receive

but the installation process claim for a MyApplication, thai is not found

Installing "cordova-plugin-sms-receive" for MyApplication

The platform "MyApplication" does not appear to be a valid cordova p
latform. It is missing API.js. MyApplication not supported.

All other plugins have installed properly so far

Thank you,
Michele

**Comment by andreszs** [comment]
It works fine without Ionic, I can't help you with that, sorry. Try to ask for support in the Ionic forums.
