### ISSUE TITLE
The plugin cordova-plugin-sms-receive is not present

### ISSUE THREAD

**Issue by sctaix** [andreszs/cordova-plugin-sms-receive#4]
I install this plugin with "cordova plugin app cordova-plugin-sms-receive"

then, download demo folder with script folder and replace my index.html to demo index.html and script folder copied same folder in index.html

STATUS message is "the plugin cordova_plugin_sms_receive is not preset"

what did i miss?

**Comment by andreszs** [comment]
Did you mean "cordova plugin **add** cordova-plugin-sms-receive"? The message you get means the plugin is not properly installed.

**Comment by sctaix** [comment]
never mind. I fixed!

**Comment by sumorox** [comment]
I am also getting same error. Can't fix it yet.

**Comment by balap777** [comment]
> never mind. I fixed!

can you please tell me how did you fix the issue it would be a grate help

**Comment by balap777** [comment]
facing the same issue and unable to find the solution  attaching the screen shot please help me to solve this problem thanks in advance

![image](https://user-images.githubusercontent.com/42376010/52964261-e1b8bd80-33c7-11e9-9803-df2a9da9aed3.png)
