### ISSUE TITLE
Migration to SMS retriever API

### ISSUE THREAD

**Issue by hrhosni** [andreszs/cordova-plugin-sms-receive#5]
Hello,

Thank you for the plugin. 
Just wondering if you have any plans to modify it to stop requiring the RECEIVE_SMS permission and use this instead: https://developers.google.com/identity/sms-retriever/overview?
Since Android is banning apps that request the RECEIVE_SMS permission.

Thanks!

**Comment by vedantpatil** [comment]
Thanks for your plugin, it helped us a lot. We are also waiting for the changes related to Google SMS Retriever API plugin updates.. Suggest if you are planning to update.
Thanks

**Comment by akshgods** [comment]
got notification from google play store , they will remove our app on jan 9 th if we not remove or change plugin

**Comment by dpa99c** [comment]
A work-in-progress alternative: [ionic-native-sms-retriever-plugin-master](https://github.com/hanatharesh2712/ionic-native-sms-retriever-plugin-master)

**Comment by SenagasettiRamesh** [comment]
you can give a trial on <a href='https://github.com/SenagasettiRamesh/cordova-plugin-sms-retriever-api'>this</a>!!

**Comment by andreszs** [comment]
Please migrate to the new [**cordova-plugin-sms-retriever**](https://github.com/andreszs/cordova-plugin-sms-retriever) based on the SMS Retriever API. Sorry for the delay.
