### ISSUE TITLE
error: reference to put is ambiguous

### ISSUE THREAD

**Issue by pmartelletti** [andreszs/cordova-plugin-sms-receive#6]
Seems like Java 8 is not liking passing null to JSON.put() directly. If you replace SMSReceive.java:105 with:

```
json.put(keys[j], JSONObject.NULL);
```

that should be fixed. 😄

**Comment by pmartelletti** [comment]
@andreszs ping

**Comment by andreszs** [comment]
Thanks, your fix has been implemented.

I'd recommend migrating to the new [**cordova-plugin-sms-retriever**](https://github.com/andreszs/cordova-plugin-sms-retriever) based on the **SMS Retriever API** for reading verification SMS without the need of additional SMS permissions.
