### ISSUE TITLE
How to get all sms in my Inbox

### ISSUE THREAD

**Issue by Imam-N** [andreszs/cordova-plugin-sms-receive#7]
This is not an Issue ;

Just Needed : Any possible to get all messages at my Inbox and Sent Items ?

**Comment by andreszs** [comment]
Not with this plugin... also, now Google does not allow ANY app to access SMS folders by any means, unless your app has been specifically and individually approved by them to do so. I assume they only grant access to SMS management apps, if they find it worth publishing.
