### ISSUE TITLE
If a Sms body contains more than 140 characters the text message gets reduced

### ISSUE THREAD

**Issue by Diptyajit1994** [andreszs/cordova-plugin-sms-receive#8]
The incoming sms receiver only returns 140 characters in **onSMSArrive**  
`document.addEventListener('onSMSArrive', function(e) {
	console.log('onSMSArrive()');
	var IncomingSMS = e.data;
	console.log('sms.body:' + IncomingSMS.body);
	/* the incomingSMS.body shows only 140 character the rest of the sms body is missing*/
	console.log(JSON.stringify(IncomingSMS));
});`

**Comment by hamzajaradat999** [comment]
Hello, Can u please provide how you did the implementation in your code? because its not working for me

**Comment by Diptyajit1994** [comment]
@hamzajaradat999  u are not able to receive sms??

**Comment by hamzajaradat999** [comment]
@Diptyajit1994 i didn,t been able to run it all of the plugin maybe i put the code in a wrong way

**Comment by Diptyajit1994** [comment]
Can u share your code only then i will be able to help you solve the issue.

**Comment by hamzajaradat999** [comment]
```
declare var sms:any;
ReadSMS(){
        var IncomingSMS
          sms.startWatch(function() {
            console.log('smsreceive: watching `started');`
        }, function() {
            console.warn('smsreceive: failed to start watching');
        });

          document.addEventListener('onSMSArrive', function(e) {
          console.log('onSMSArrive()');
          IncomingSMS = e
          console.log(JSON.stringify(IncomingSMS));
      });
      if(IncomingSMS!==undefined)
      sms.stopWatch(function() {
        console.log('smsreceive: watching stopped');
    }, function() {
        console.warn('smsreceive: failed to stop watching');
    });

      
   }
```

im using ionic for this project
im missing something but i dont know where,
sorry for my low skills
```

**Comment by Diptyajit1994** [comment]
@hamzajaradat999  u have to have separate set of codes for starting a watcher and stopping a watcher and a separate sms onarrive listener code as follows -

```
ReadSMS(){
	if(typeof (SMSReceive) === 'undefined') {
		// Error: plugin not installed
		console.warn('SMSReceive: plugin not present');
	} else {
		// Initialize incoming SMS event listener
		document.addEventListener('onSMSArrive', function(e) {
			console.log('onSMSArrive()');
			self.stopSmsWatch()
			var IncomingSMS = e.data;
			console.log('sms.address:' + IncomingSMS.address);
			console.log('sms.body:' + IncomingSMS.body);

		});
	}
}
stopSmsWatch(){
	SMSReceive.stopWatch(function() {
		console.log('SMS Watching stopped')
	}, function() {
		console.log('Plugin failed to stop watching')
	});
}
```

**Comment by hamzajaradat999** [comment]
@Diptyajit1994 sorry man for the bother here but i have done this:
 i checked the plugin list using "cordova plugin -l" and it was listed as "cordova-plugin-sms-receive 1.0.2 "SMS Receive" and i copied the methods that you provided and placed them as is so they give me red underlines under every
SMSReceive , self.stopSmsWatch() but i change it to 'this' and under 'data' of e.data  
i get this error and im not surprised
`[13:15:22]  typescript: ...h IOS Platform/asdasd-Customer/src/pages/code-verification/code-verification.ts, line: 155 
            Cannot find name 'SMSReceive'.

     L155:  if(typeof (SMSReceive) === 'undefined') {
     L156:  // Error: plugin not installed

[13:15:22]  typescript: ...h IOS Platform/asasd-Customer/src/pages/code-verification/code-verification.ts, line: 163 
            Property 'data' does not exist on type 'Event'.

     L162:  this.stopSmsWatch()
     L163:  var IncomingSMS = e.data;
     L164:  console.log('sms.address:' + IncomingSMS.address);

[13:15:22]  typescript: ...h IOS Platform/asdasd-Customer/src/pages/code-verification/code-verification.ts, line: 171 
            Cannot find name 'SMSReceive'.

     L170:  stopSmsWatch(){
     L171:  SMSReceive.stopWatch(function() {
     L172:  console.log('SMS Watching stopped')

[13:15:22]  typescript: ...h IOS Platform/asdasd-Customer/src/pages/code-verification/code-verification.ts, line: 178 
            Cannot find name 'SMSReceive'.

     L177:  startSmsWatch(){
     L178:  SMSReceive.startWatch(function() {
     L179:  console.log('SMS Watching started')

[13:15:22]  ionic-app-script task: "build" 
[13:15:22]  Error: Failed to transpile program 
Error: Failed to transpile program
    at new BuildError (D:\Work\Projects\With IOS Platform\asdasd-Customer\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at D:\Work\Projects\With IOS Platform\asdasd-Customer\node_modules\@ionic\app-scripts\dist\transpile.js:159:20
    at new Promise (<anonymous>)
    at transpileWorker (D:\Work\Projects\With IOS Platform\asdasd-Customer\node_modules\@ionic\app-scripts\dist\transpile.js:107:12)
    at Object.transpile (D:\Work\Projects\With IOS Platform\asdasdeProfix-Customer\node_modules\@ionic\app-scripts\dist\transpile.js:64:12)
    at D:\Work\Projects\With IOS Platform\asdasd-Customer\node_modules\@ionic\app-scripts\dist\build.js:109:82
[ERROR] An error occurred while running subprocess ionic-app-scripts.

        ionic-app-scripts build --target cordova --platform android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.` 
i did not have any issues dealing with this plugin [https://www.npmjs.com/package/cordova-plugin-sms](url) and worked with me but it need money for commercial use 
sorry again for the bother

**Comment by Diptyajit1994** [comment]
@hamzajaradat999 try this plugin  - https://github.com/rampicos/Cordova-SMS-Plugin

**Comment by hamzajaradat999** [comment]
@Diptyajit1994 i will try it and see what will happen with it

**Comment by andriyleu** [comment]
@hamzajaradat999 hello, you need to do few things to make the plugin work:

1- Besides installing the plugin itself with cordova install also with npm
2- Add following line wherever you use the plugin under your importe:
declare var SMSReceive: any;

With this you will solve the problems related to "Cannot find name SMSReceive".

Regarding to other problems, you need to use Typescript functions instead of JavaScript, so:

Instead of function () { }:

Use: () => { }

I had the same issues at work few weeks ago and figured it out, good luck ^_^

**Comment by yurik94** [comment]
SMS are still trimmed....

**Comment by yurik94** [comment]
![image](https://user-images.githubusercontent.com/13189646/55279314-d4bcb180-5317-11e9-9359-8c1f4d912e1e.png)
Here is it :D

**Comment by yurik94** [comment]
SMS are still trimmed....

here's why:

![image](https://user-images.githubusercontent.com/13189646/55279341-43017400-5318-11e9-84c6-c0da9210d88c.png)

It should cycle through the array and concat the body!

**Comment by andreszs** [comment]
@yurik94 Thanks, feel free to create a PR if you can handly it in order to update the plugin.

Anyway, I suggest using the new [cordova-plugin-sms-retriever](https://github.com/andreszs/cordova-plugin-sms-retriever) plugin in order to use the new method without SMS permission request.

**Comment by yurik94** [comment]
I have an app which requires sending and receiving SMS to customers so I
can't use an external API (user doesn't want to pay as he has free SMS
ehehe)

Il giorno ven 5 apr 2019 alle ore 18:09 Andrés <notifications@github.com>
ha scritto:

**Comment by andersborgabiro** [comment]
I have the same problem: the phone's SMS app shows the whole message, but my app only gets the first chunk. My scenario is similar to @yurik94.

**Comment by Jerome-bxl** [comment]
Following the advice from @yurik94 to get the entire message if body length bigger than 153 letters :

I am not a JAVA dev at all so, feel free to correct the code below  :
You can adjust the code following the few lines marked as   
```
/* CHANGE START ------------ */
...
/* CHANGE STOP ------------ */
```

```
	protected void createIncomingSMSReceiver() {
		this.mReceiver = new BroadcastReceiver() {
			public void onReceive(Context context, Intent intent) {
				if (intent.getAction().equals(SMS_RECEIVED_ACTION)) {
					// Create SMS container
					SmsMessage smsmsg = null;
					/* CHANGE START ------------ */
					String smsBody = "";
					/* CHANGE STOP ------------ */
					// Determine which API to use
					if (Build.VERSION.SDK_INT >= 19) {
						try {
							/* CHANGE START ------------ */
							//SmsMessage[] sms = Telephony.Sms.Intents.getMessagesFromIntent(intent);
							//smsmsg = sms[0];
							for (SmsMessage smsMessage : Telephony.Sms.Intents.getMessagesFromIntent(intent)) {
				                smsBody += smsMessage.getMessageBody();
				                smsmsg = smsMessage; 
				            }
				            /* CHANGE STOP ------------ */
						} catch (Exception e) {
							Log.d(LOG_TAG, e.getMessage());
						}
					} else {
						Bundle bundle = intent.getExtras();
						Object pdus[] = (Object[]) bundle.get("pdus");
						try {
							smsmsg = SmsMessage.createFromPdu((byte[]) pdus[0]);
						} catch (Exception e) {
							Log.d(LOG_TAG, e.getMessage());
						}
					}
					// Get SMS contents as JSON
					if(smsmsg != null) {
						/* CHANGE START ------------ */
						JSONObject jsms = SMSReceive.this.getJsonFromSmsMessage(smsmsg, smsBody);
						/* CHANGE STOP ------------ */
						SMSReceive.this.onSMSArrive(jsms);
						Log.d(LOG_TAG, jsms.toString());
					}else{
						Log.d(LOG_TAG, "smsmsg is null");
					}
				}
			}
		};
		IntentFilter filter = new IntentFilter(SMS_RECEIVED_ACTION);
		try {
			webView.getContext().registerReceiver(this.mReceiver, filter);
		} catch (Exception e) {
			Log.d(LOG_TAG, "error registering broadcast receiver: " + e.getMessage());
		}
	}
```


```
/* CHANGE START ------------ */
private JSONObject getJsonFromSmsMessage(SmsMessage sms, String smsBody) {
/* CHANGE STOP ------------ */
	JSONObject json = new JSONObject();
	try {
		json.put( "address", sms.getOriginatingAddress() );
		/* CHANGE START ------------ */
		json.put( "body", smsBody ); // May need sms.getMessageBody.toString()
		/* CHANGE STOP ------------ */
		json.put( "date_sent", sms.getTimestampMillis() );
		json.put( "date", System.currentTimeMillis() );
		json.put( "service_center", sms.getServiceCenterAddress());
	}
	catch (Exception e) {
		Log.d(LOG_TAG, e.getMessage());
	}
	return json;
}
```

Thanks for this plugin, very helpfull :)

**Comment by andreszs** [comment]
Hi, please download version 2.0.0 which fixed the SMS characters limit and other issues as well.
